# HTML Templates as strings
html_templates = {
    'detect.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>AI Detector - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}" class="active"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>AI Content Detector</h1>
            <p>Paste text below to check if it will be flagged as AI-generated by detection tools.</p>

            {% if payment_required %}
                <div class="payment-required">
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i> 
                        Payment required: You need to make a payment to use this feature with your current plan.
                    </div>
                    <div class="payment-buttons">
                        <a href="{{ url_for('payment') }}" class="button highlight"><i class="fas fa-credit-card"></i> Make Payment</a>
                        <a href="{{ url_for('upgrade') }}" class="button"><i class="fas fa-exchange-alt"></i> Change Plan</a>
                    </div>
                </div>
            {% else %}
                {% if message %}
                    <div class="alert alert-info">{{ message }}</div>
                {% endif %}
                <form method="post">
                    <div class="form-group">
                        <label for="text">Text to Analyze</label>
                        <textarea id="text" name="text" rows="10" required></textarea>
                    </div>
                    <button type="submit" class="button highlight"><i class="fas fa-search"></i> Analyze</button>
                </form>

                {% if result %}
                    <div class="result-section">
                        <h2>Detection Results</h2>
                        <div class="detection-result">
                            <div class="detection-meters">
                                <div class="meter-container">
                                    <div class="meter-label">AI Probability</div>
                                    <div class="meter">
                                        <div class="meter-bar" style="width: {{ result.ai_score }}%; background-color: rgba(255, 0, 0, {{ result.ai_score / 100 }})"></div>
                                    </div>
                                    <div class="meter-value">{{ result.ai_score }}%</div>
                                </div>
                                <div class="meter-container">
                                    <div class="meter-label">Human Probability</div>
                                    <div class="meter">
                                        <div class="meter-bar" style="width: {{ result.human_score }}%; background-color: rgba(0, 255, 0, {{ result.human_score / 100 }})"></div>
                                    </div>
                                    <div class="meter-value">{{ result.human_score }}%</div>
                                </div>
                            </div>

                            <div class="detection-analysis">
                                <h3>Detailed Analysis</h3>
                                <div class="analysis-item">
                                    <div class="analysis-label">Formal Language:</div>
                                    <div class="analysis-meter">
                                        <div class="analysis-bar" style="width: {{ result.analysis.formal_language }}%"></div>
                                    </div>
                                    <div class="analysis-value">{{ result.analysis.formal_language }}%</div>
                                </div>
                                <div class="analysis-item">
                                    <div class="analysis-label">Repetitive Patterns:</div>
                                    <div class="analysis-meter">
                                        <div class="analysis-bar" style="width: {{ result.analysis.repetitive_patterns }}%"></div>
                                    </div>
                                    <div class="analysis-value">{{ result.analysis.repetitive_patterns }}%</div>
                                </div>
                                <div class="analysis-item">
                                    <div class="analysis-label">Sentence Uniformity:</div>
                                    <div class="analysis-meter">
                                        <div class="analysis-bar" style="width: {{ result.analysis.sentence_uniformity }}%"></div>
                                    </div>
                                    <div class="analysis-value">{{ result.analysis.sentence_uniformity }}%</div>
                                </div>
                            </div>

                            <div class="detection-recommendation">
                                {% if result.ai_score > 70 %}
                                    <div class="recommendation high-risk">
                                        <i class="fas fa-exclamation-circle"></i>
                                        <strong>High Risk of Detection</strong>
                                        <p>This content is likely to be flagged as AI-generated. Consider using our Humanize tool to reduce AI markers.</p>
                                        <a href="{{ url_for('humanize') }}" class="button highlight"><i class="fas fa-magic"></i> Humanize This Text</a>
                                    </div>
                                {% elif result.ai_score > 40 %}
                                    <div class="recommendation medium-risk">
                                        <i class="fas fa-exclamation-triangle"></i>
                                        <strong>Medium Risk of Detection</strong>
                                        <p>This content has some AI indicators that might be detected. Using our Humanize tool can help make it more natural.</p>
                                        <a href="{{ url_for('humanize') }}" class="button"><i class="fas fa-magic"></i> Humanize This Text</a>
                                    </div>
                                {% else %}
                                    <div class="recommendation low-risk">
                                        <i class="fas fa-check-circle"></i>
                                        <strong>Low Risk of Detection</strong>
                                        <p>This content appears natural and is unlikely to be flagged as AI-generated.</p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',

    'api_integration.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>API Integration - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}" class="active"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>API Integrations</h1>
            <p>Connect Andikar AI with other AI detection tools for comprehensive analysis.</p>

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <div class="api-section">
                <h2><i class="fas fa-plug"></i> Connect External APIs</h2>
                <p>Enter your API keys to integrate with third-party AI detection tools.</p>

                <form method="post" class="api-form">
                    <div class="api-card">
                        <div class="api-logo">
                            <i class="fas fa-robot"></i>
                            <h3>GPT Zero</h3>
                        </div>
                        <div class="api-description">
                            <p>GPT Zero helps you determine if text was written by AI tools like ChatGPT.</p>
                        </div>
                        <div class="form-group">
                            <label for="gpt_zero_key">GPT Zero API Key</label>
                            <input type="text" id="gpt_zero_key" name="gpt_zero_key" value="{{ api_keys.gpt_zero }}">
                        </div>
                    </div>

                    <div class="api-card">
                        <div class="api-logo">
                            <i class="fas fa-fingerprint"></i>
                            <h3>Originality.ai</h3>
                        </div>
                        <div class="api-description">
                            <p>Originality.ai detects AI-generated content and checks for plagiarism.</p>
                        </div>
                        <div class="form-group">
                            <label for="originality_key">Originality.ai API Key</label>
                            <input type="text" id="originality_key" name="originality_key" value="{{ api_keys.originality }}">
                        </div>
                    </div>

                    <button type="submit" class="button highlight"><i class="fas fa-save"></i> Save API Keys</button>
                </form>
            </div>

            <div class="api-info">
                <h3>How to Get API Keys</h3>
                <ul>
                    <li>
                        <strong>GPT Zero:</strong> Visit <a href="#" class="external-link">gptzero.me</a> and create an account. 
                        Navigate to the API section to generate your key.
                    </li>
                    <li>
                        <strong>Originality.ai:</strong> Sign up at <a href="#" class="external-link">originality.ai</a>. 
                        Go to your account settings to find your API key.
                    </li>
                </ul>
                <p class="api-note">
                    <i class="fas fa-info-circle"></i> Your API keys are stored securely and only used for detection operations initiated by you.
                </p>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',

    'community.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Community - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}" class="active"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Join Our Community</h1>
            <p>Connect with other Andikar AI users to share tips, ask questions, and stay updated.</p>

            <div class="community-section">
                <div class="community-card telegram">
                    <div class="community-icon">
                        <i class="fab fa-telegram"></i>
                    </div>
                    <div class="community-content">
                        <h2>Telegram Group</h2>
                        <p>Join our active Telegram community for real-time support, tips, and discussions.</p>
                        <a href="https://t.me/andikarai" target="_blank" class="button highlight">
                            <i class="fab fa-telegram"></i> Join Telegram Group
                        </a>
                    </div>
                </div>

                <div class="community-card">
                    <div class="community-icon">
                        <i class="fas fa-envelope"></i>
                    </div>
                    <div class="community-content">
                        <h2>Newsletter</h2>
                        <p>Subscribe to our newsletter for the latest updates, features, and AI detection tips.</p>
                        <form class="newsletter-form">
                            <input type="email" placeholder="Your email address" required>
                            <button type="submit" class="button">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="community-section">
                <div class="community-card">
                    <div class="community-icon">
                        <i class="fas fa-graduation-cap"></i>
                    </div>
                    <div class="community-content">
                        <h2>Tutorials & Resources</h2>
                        <p>Access our growing library of guides on avoiding AI detection and creating human-like content.</p>
                        <div class="resource-links">
                            <a href="#" class="resource-link">
                                <i class="fas fa-book"></i> Beginner's Guide to AI Detection
                            </a>
                            <a href="#" class="resource-link">
                                <i class="fas fa-video"></i> Video: Humanizing AI Text
                            </a>
                            <a href="#" class="resource-link">
                                <i class="fas fa-file-alt"></i> Best Practices for Academic Writing
                            </a>
                        </div>
                    </div>
                </div>

                <div class="community-card">
                    <div class="community-icon">
                        <i class="fas fa-headset"></i>
                    </div>
                    <div class="community-content">
                        <h2>Support</h2>
                        <p>Need help with Andikar AI? Our support team is ready to assist you.</p>
                        <a href="mailto:support@andikarai.com" class="button">
                            <i class="fas fa-envelope"></i> Contact Support
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',

    'download.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Download Desktop App - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Download Andikar AI Desktop Application</h1>
            <p>Get our powerful desktop application for a seamless offline experience.</p>

            <div class="download-section">
                <div class="features-list">
                    <h2>Desktop App Features</h2>
                    <ul>
                        <li><i class="fas fa-check-circle"></i> Work offline without internet connection</li>
                        <li><i class="fas fa-check-circle"></i> Process larger text volumes</li>
                        <li><i class="fas fa-check-circle"></i> Faster processing and response times</li>
                        <li><i class="fas fa-check-circle"></i> Advanced humanization algorithms</li>
                        <li><i class="fas fa-check-circle"></i> Integration with word processors</li>
                        <li><i class="fas fa-check-circle"></i> Batch processing capabilities</li>
                    </ul>
                </div>

                <div class="download-options">
                    <h2>Available for All Platforms</h2>
                    <div class="download-cards">
                        <div class="download-card">
                            <div class="platform-icon"><i class="fab fa-windows"></i></div>
                            <h3>Windows</h3>
                            <p>Windows 10/11<br>64-bit</p>
                            <a href="#" class="button download-button"><i class="fas fa-download"></i> Download for Windows</a>
                        </div>

                        <div class="download-card">
                            <div class="platform-icon"><i class="fab fa-apple"></i></div>
                            <h3>macOS</h3>
                            <p>macOS 10.15+<br>Intel & Apple Silicon</p>
                            <a href="#" class="button download-button"><i class="fas fa-download"></i> Download for macOS</a>
                        </div>

                        <div class="download-card">
                            <div class="platform-icon"><i class="fab fa-linux"></i></div>
                            <h3>Linux</h3>
                            <p>Ubuntu, Debian<br>CentOS, Fedora</p>
                            <a href="#" class="button download-button"><i class="fas fa-download"></i> Download for Linux</a>
                        </div>
                    </div>

                    <div class="premium-note">
                        <i class="fas fa-crown"></i>
                        <p>Desktop application is available for Premium subscribers only. <a href="{{ url_for('upgrade') }}">Upgrade your plan</a> to access.</p>
                    </div>
                </div>
            </div>

            <div class="desktop-screenshot">
                <h2>App Preview</h2>
                <div class="screenshot-container">
                    <div class="app-screenshot"></div>
                    <div class="screenshot-caption">Andikar AI Desktop Interface</div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',

    'faq.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>FAQ - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Frequently Asked Questions</h1>
            <p>Find answers to common questions about Andikar AI.</p>

            <div class="faq-container">
                <div class="faq-categories">
                    <button class="faq-category active" data-category="general">General</button>
                    <button class="faq-category" data-category="humanize">Humanization</button>
                    <button class="faq-category" data-category="detection">AI Detection</button>
                    <button class="faq-category" data-category="account">Account & Billing</button>
                    <button class="faq-category" data-category="technical">Technical</button>
                </div>

                <div class="faq-list" id="general">
                    <div class="faq-item">
                        <div class="faq-question">
                            <span>What is Andikar AI?</span>
                            <i class="fas fa-chevron-down"></i>
                        </div>
                        <div class="faq-answer">
                            <p>Andikar AI is a platform that helps transform AI-generated content into natural, human-like text that can bypass AI detection tools. It also provides AI detection capabilities to check if your content might be flagged as AI-generated.</p>
                        </div>
                    </div>

                    <div class="faq-item">
                        <div class="faq-question">
                            <span>How does Andikar AI work?</span>
                            <i class="fas fa-chevron-down"></i>
                        </div>
                        <div class="faq-answer">
                            <p>Andikar AI analyzes AI-generated text, identifies patterns that are typically flagged by AI detectors, and applies various transformations to make the text appear more human-written. These include adding natural language variations, adjusting sentence structures, and incorporating subtle linguistic nuances characteristic of human writing.</p>
                        </div>
                    </div>

                    <div class="faq-item">
                        <div class="faq-question">
                            <span>Is it ethical to use Andikar AI?</span>
                            <i class="fas fa-chevron-down"></i>
                        </div>
                        <div class="faq-answer">
                            <p>Andikar AI is designed as a tool to help users refine and personalize AI-generated content. We encourage ethical use for legitimate purposes such as content creation, academic writing assistance, and business communications. Users should always follow the guidelines and policies of their organizations regarding AI content use.</p>
                        </div>
                    </div>
                </div>

                <!-- More FAQ categories would go here -->
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',

    'index.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Andikar AI - Humanize AI Content</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="container">
        <div class="glass-panel">
            <div class="logo">Andikar AI</div>
            <h1>Transform AI Content to Human-Like Writing</h1>
            <p>Andikar AI helps you convert AI-generated content into natural, human-like text that passes AI detection tools.</p>
            <div class="features-highlight">
                <div class="feature">
                    <div class="feature-icon"><i class="fas fa-comment-alt"></i></div>
                    <h3>Content Humanizer</h3>
                    <p>Transform AI text into natural human writing</p>
                </div>
                <div class="feature">
                    <div class="feature-icon"><i class="fas fa-search"></i></div>
                    <h3>AI Detector</h3>
                    <p>Check if your content will be flagged as AI-generated</p>
                </div>
                <div class="feature">
                    <div class="feature-icon"><i class="fas fa-plug"></i></div>
                    <h3>API Integration</h3>
                    <p>Connect with major AI detection tools</p>
                </div>
            </div>
            <div class="buttons">
                <a href="{{ url_for('login') }}" class="button">Login</a>
                <a href="{{ url_for('register') }}" class="button highlight">Register</a>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'login.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Login - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="container">
        <div class="glass-panel">
            <div class="logo">Andikar AI</div>
            <h1>Login</h1>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <form method="post">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit" class="button highlight">Login</button>
            </form>
            <p>Don't have an account? <a href="{{ url_for('register') }}">Register</a></p>
            <a href="{{ url_for('index') }}" class="back-link">Back to Home</a>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'register.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Register - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="container">
        <div class="glass-panel">
            <div class="logo">Andikar AI</div>
            <h1>Register</h1>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <form method="post">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number (optional)</label>
                    <input type="tel" id="phone" name="phone" placeholder="e.g., 254712345678">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label>Select Plan</label>
                    {% for plan_name, plan_details in pricing_plans.items() %}
                    <div class="plan-option">
                        <input type="radio" id="{{ plan_name }}" name="plan_type" value="{{ plan_name }}" {% if plan_name == 'Free' %}checked{% endif %} required>
                        <label for="{{ plan_name }}">
                            <strong>{{ plan_name }}</strong>: KES {{ plan_details.price }} - {{ plan_details.description }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
                <button type="submit" class="button highlight">Register</button>
            </form>
            <p>Already have an account? <a href="{{ url_for('login') }}">Login</a></p>
            <a href="{{ url_for('index') }}" class="back-link">Back to Home</a>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'dashboard.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}" class="active"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel dashboard">
            <h1>Welcome to your Dashboard</h1>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="dashboard-card">
                <h2>Account Overview</h2>
                <div class="info-row">
                    <div class="info-label">Username:</div>
                    <div class="info-value">{{ session.user_id }}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Plan:</div>
                    <div class="info-value">{{ user.plan }}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Word Limit:</div>
                    <div class="info-value">{{ plan.word_limit }} words</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Words Used:</div>
                    <div class="info-value">{{ user.words_used }} words</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Payment Status:</div>
                    <div class="info-value {% if user.payment_status == 'Paid' %}status-paid{% else %}status-pending{% endif %}">
                        {{ user.payment_status }}
                    </div>
                </div>
            </div>
            <div class="dashboard-actions">
                <div class="action-section">
                    <h3>Tools</h3>
                    <div class="action-buttons">
                        <a href="{{ url_for('humanize') }}" class="button"><i class="fas fa-magic"></i> Humanize Text</a>
                        <a href="{{ url_for('detect') }}" class="button"><i class="fas fa-search"></i> AI Detector</a>
                        <a href="{{ url_for('download') }}" class="button"><i class="fas fa-download"></i> Desktop App</a>
                    </div>
                </div>
                <div class="action-section">
                    <h3>Account</h3>
                    <div class="action-buttons">
                        <a href="{{ url_for('account') }}" class="button"><i class="fas fa-user-cog"></i> Manage Account</a>
                        {% if user.payment_status == 'Pending' and user.plan != 'Free' %}
                        <a href="{{ url_for('payment') }}" class="button highlight"><i class="fas fa-credit-card"></i> Make Payment</a>
                        {% endif %}
                        <a href="{{ url_for('upgrade') }}" class="button"><i class="fas fa-arrow-up"></i> Upgrade Plan</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'humanize.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Humanize Text - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}" class="active"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Humanize AI-generated Text</h1>
            <p>Paste your text below and transform it into natural, human-like content that bypasses AI detection.</p>
            <p class="info">Your word limit: <strong>{{ word_limit }} words</strong></p>

            {% if payment_required %}
                <div class="payment-required">
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i> 
                        Payment required: You need to make a payment to use this feature with your {{ session.user_id }} account.
                    </div>
                    <div class="payment-buttons">
                        <a href="{{ url_for('payment') }}" class="button highlight"><i class="fas fa-credit-card"></i> Make Payment</a>
                        <a href="{{ url_for('upgrade') }}" class="button"><i class="fas fa-exchange-alt"></i> Change Plan</a>
                    </div>
                </div>
            {% else %}
                {% if message %}
                    <div class="alert {% if 'truncated' in message %}alert-warning{% else %}alert-info{% endif %}">{{ message }}</div>
                {% endif %}
                <form method="post">
                    <div class="form-group">
                        <label for="original_text">Original Text</label>
                        <textarea id="original_text" name="original_text" rows="10" required></textarea>
                    </div>
                    <button type="submit" class="button highlight"><i class="fas fa-magic"></i> Humanize</button>
                </form>
                {% if humanized_text %}
                    <div class="result-section">
                        <h2>Humanized Result</h2>
                        <div class="humanized-text">{{ humanized_text }}</div>
                        <div class="result-actions">
                            <button class="button" onclick="copyToClipboard()"><i class="fas fa-copy"></i> Copy to Clipboard</button>
                            <button class="button" onclick="downloadText()"><i class="fas fa-download"></i> Download as TXT</button>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'account.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>My Account - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}" class="active"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Account Management</h1>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="account-section">
                <h2><i class="fas fa-user"></i> Account Details</h2>
                <div class="info-row">
                    <div class="info-label">Username:</div>
                    <div class="info-value">{{ session.user_id }}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Joined Date:</div>
                    <div class="info-value">{{ user.joined_date }}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Current Plan:</div>
                    <div class="info-value">{{ user.plan }} ({{ plan.word_limit }} words)</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Words Used:</div>
                    <div class="info-value">{{ user.words_used }} / {{ plan.word_limit }}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Payment Status:</div>
                    <div class="info-value {% if user.payment_status == 'Paid' %}status-paid{% else %}status-pending{% endif %}">
                        {{ user.payment_status }}
                    </div>
                </div>
            </div>

            <div class="account-section">
                <h2><i class="fas fa-file-invoice"></i> Billing History</h2>
                {% if transactions %}
                    <table class="transactions-table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Transaction ID</th>
                                <th>Amount (KES)</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaction in transactions %}
                                <tr>
                                    <td>{{ transaction.date }}</td>
                                    <td>{{ transaction.transaction_id }}</td>
                                    <td>{{ transaction.amount }}</td>
                                    <td class="status-{{ transaction.status|lower }}">{{ transaction.status }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No transactions found.</p>
                {% endif %}
            </div>

            <div class="account-actions">
                {% if user.payment_status == 'Pending' and user.plan != 'Free' %}
                    <a href="{{ url_for('payment') }}" class="button highlight"><i class="fas fa-credit-card"></i> Make Payment</a>
                {% endif %}
                <a href="{{ url_for('upgrade') }}" class="button"><i class="fas fa-arrow-up"></i> Upgrade Plan</a>
                <a href="{{ url_for('api_integration') }}" class="button"><i class="fas fa-plug"></i> API Integrations</a>
                <a href="{{ url_for('download') }}" class="button"><i class="fas fa-download"></i> Download Desktop App</a>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'pricing.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Pricing - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}" class="active"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Pricing Plans</h1>
            <p class="pricing-subtitle">Choose the plan that fits your needs</p>
            <div class="pricing-cards">
                {% for plan_name, plan_details in pricing_plans.items() %}
                    <div class="pricing-card {% if plan_name == 'Premium' %}premium{% endif %}">
                        <div class="plan-badge {% if plan_name == 'Premium' %}premium-badge{% endif %}">
                            {% if plan_name == 'Premium' %}RECOMMENDED{% endif %}
                            {% if plan_name == 'Free' %}START HERE{% endif %}
                        </div>
                        <h2>{{ plan_name }}</h2>
                        <div class="price">
                            KES {{ plan_details.price }}
                            <span>{% if plan_name != 'Free' %}/month{% else %}Forever{% endif %}</span>
                        </div>
                        <ul class="features">
                            <li><i class="fas fa-check"></i> {{ plan_details.word_limit }} words per round</li>
                            <li><i class="fas fa-check"></i> AI Content Humanizer</li>
                            <li><i class="fas fa-check"></i> 24/7 Support</li>
                            <li><i class="fas fa-check"></i> Account Management</li>

                            {% if plan_name == 'Premium' or plan_name == 'Basic' %}
                                <li><i class="fas fa-check"></i> AI Detection Tool</li>
                                <li><i class="fas fa-check"></i> API Integrations</li>
                            {% else %}
                                <li class="feature-disabled"><i class="fas fa-times"></i> AI Detection Tool</li>
                                <li class="feature-disabled"><i class="fas fa-times"></i> API Integrations</li>
                            {% endif %}

                            {% if plan_name == 'Premium' %}
                                <li><i class="fas fa-check"></i> Priority Processing</li>
                                <li><i class="fas fa-check"></i> Advanced Humanization Options</li>
                                <li><i class="fas fa-check"></i> Desktop Application</li>
                            {% else %}
                                <li class="feature-disabled"><i class="fas fa-times"></i> Priority Processing</li>
                                <li class="feature-disabled"><i class="fas fa-times"></i> Advanced Humanization</li>
                                <li class="feature-disabled"><i class="fas fa-times"></i> Desktop Application</li>
                            {% endif %}
                        </ul>
                        <a href="{{ url_for('upgrade') }}" class="button {% if plan_name == 'Premium' %}highlight{% endif %}">
                            {% if plan_name == 'Free' %}Start Free{% else %}Upgrade Now{% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'payment.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Payment - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Make Payment</h1>
            <div class="payment-details">
                <h2>Plan: {{ plan.plan }}</h2>
                <div class="price">KES {{ plan.price }}</div>
                <p>{{ plan.description }}</p>
            </div>
            <form method="post" class="payment-form">
                <div class="form-group">
                    <label for="phone_number">M-PESA Phone Number</label>
                    <input type="text" id="phone_number" name="phone_number" placeholder="e.g., 254712345678" required>
                </div>
                <p class="info">Click "Pay with M-PESA" to simulate payment. In a real system, you would receive an M-PESA prompt on your phone.</p>
                <button type="submit" class="button highlight"><i class="fas fa-credit-card"></i> Pay with M-PESA</button>
            </form>
            <div class="payment-info">
                <h3>How to Pay</h3>
                <ol>
                    <li>Enter your M-PESA registered phone number</li>
                    <li>Click "Pay with M-PESA"</li>
                    <li>A simulated payment will be processed</li>
                </ol>
                <p>Note: This is a simulated payment for development purposes. No actual charges will be made.</p>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    ''',
    'upgrade.html': '''
<!DOCTYPE html>
<html>
<head>
    <title>Upgrade Plan - Andikar AI</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="nav-logo">Andikar AI</div>
        <div class="nav-container">
            <div class="nav-left">
                <a href="{{ url_for('dashboard') }}"><i class="fas fa-home"></i> Dashboard</a>
                <a href="{{ url_for('humanize') }}"><i class="fas fa-magic"></i> Humanize Text</a>
                <a href="{{ url_for('detect') }}"><i class="fas fa-search"></i> AI Detector</a>
                <a href="{{ url_for('community') }}"><i class="fas fa-users"></i> Community</a>
            </div>
            <div class="nav-right">
                <a href="{{ url_for('pricing') }}"><i class="fas fa-tag"></i> Pricing</a>
                <a href="{{ url_for('account') }}"><i class="fas fa-user-circle"></i> My Account</a>
                <a href="{{ url_for('api_integration') }}"><i class="fas fa-plug"></i> API Integration</a>
                <a href="{{ url_for('logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="glass-panel">
            <h1>Upgrade Your Plan</h1>
            <div class="current-plan">
                <h2>Current Plan: {{ current_plan.plan }}</h2>
                <div class="info-row">
                    <div class="info-label">Price:</div>
                    <div class="info-value">KES {{ current_plan.price }}/month</div>
                </div>
                <div class="info-row">
                    <div class="info-label">Word Limit:</div>
                    <div class="info-value">{{ current_plan.word_limit }} words/month</div>
                </div>
            </div>

            {% if available_plans %}
                <form method="post" class="upgrade-form">
                    <h2>Available Plans</h2>
                    {% for plan_name, plan_details in available_plans.items() %}
                        <div class="plan-option">
                            <input type="radio" id="{{ plan_name }}" name="new_plan" value="{{ plan_name }}" required>
                            <label for="{{ plan_name }}" class="plan-label">
                                <div class="plan-name">{{ plan_name }}</div>
                                <div class="plan-price">KES {{ plan_details.price }}/month</div>
                                <div class="plan-limit">{{ plan_details.word_limit }} words/month</div>
                                <div class="plan-desc">{{ plan_details.description }}</div>
                            </label>
                        </div>
                    {% endfor %}
                    <button type="submit" class="button highlight">Upgrade Plan</button>
                </form>
            {% else %}
                <div class="alert alert-info">You are already on the highest available plan.</div>
            {% endif %}
        </div>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>
    '''
}
