import os

# Initialize templates dictionary
html_templates = {}

# Load templates from files
template_dir = 'templates'

# If template directory exists, load templates from files
if os.path.exists(template_dir):
    for filename in os.listdir(template_dir):
        if filename.endswith('.html'):
            with open(os.path.join(template_dir, filename), 'r') as f:
                template_name = filename
                html_templates[template_name] = f.read()

# Fallback templates if files not available
if 'dashboard.html' not in html_templates:
    html_templates['dashboard.html'] = """
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="container">
    <h1>Welcome to Andikar AI</h1>

    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h2>Your Subscription</h2>
                </div>
                <div class="card-body">
                    <p><strong>Plan:</strong> {{ user.plan }}</p>
                    <p><strong>Words Remaining:</strong> {{ words_remaining }}</p>
                    <p><strong>Status:</strong> 
                        {% if user.payment_status == "Paid" %}
                        <span class="badge bg-success">Paid</span>
                        {% else %}
                        <span class="badge bg-warning">Payment Required</span>
                        {% endif %}
                    </p>
                    
                    {% if user.plan != "Free" and user.payment_status != "Paid" %}
                    <div class="alert alert-warning">
                        <p>You need to complete payment to access premium features.</p>
                        <a href="{{ url_for('pricing') }}" class="btn btn-warning">Complete Payment</a>
                    </div>
                    {% endif %}
                    
                    <div class="mt-3">
                        <a href="{{ url_for('pricing') }}" class="btn btn-primary">Manage Subscription</a>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    <h2>Account Info</h2>
                </div>
                <div class="card-body">
                    <p><strong>Joined:</strong> {{ user.joined_date }}</p>
                    <p><strong>Account Type:</strong> {{ user.plan }}</p>
                    <div class="mt-3">
                        <a href="{{ url_for('account') }}" class="btn btn-outline-primary">Manage Account</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card mb-4">
                <div class="card-header">
                    <h2>Features</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h3 class="h5">Humanize Text</h3>
                                    <p>Make AI-generated text sound more human.</p>
                                    <a href="{{ url_for('humanize') }}" class="btn btn-primary">Humanize Text</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h3 class="h5">AI Detection</h3>
                                    <p>Check if text was generated by AI.</p>
                                    <a href="{{ url_for('detect') }}" class="btn btn-primary">Detect AI</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="card mb-3">
                        <div class="card-body">
                            <h3 class="h5">API Integration</h3>
                            <p>Integrate with third-party AI detection services.</p>
                            <a href="{{ url_for('api_integration') }}" class="btn btn-outline-primary">Manage API Keys</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h2>Usage Stats</h2>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td><strong>Total Word Limit:</strong></td>
                            <td>{{ plan.word_limit }}</td>
                        </tr>
                        <tr>
                            <td><strong>Words Remaining:</strong></td>
                            <td>{{ words_remaining }}</td>
                        </tr>
                        <tr>
                            <td><strong>Words Used:</strong></td>
                            <td>{{ plan.word_limit - words_remaining }}</td>
                        </tr>
                    </table>
                    
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" 
                             style="width: {{ (plan.word_limit - words_remaining) / plan.word_limit * 100 }}%;"
                             aria-valuenow="{{ plan.word_limit - words_remaining }}" 
                             aria-valuemin="0" 
                             aria-valuemax="{{ plan.word_limit }}">
                            {{ ((plan.word_limit - words_remaining) / plan.word_limit * 100) | round }}%
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
"""

if 'account.html' not in html_templates:
    html_templates['account.html'] = """
{% extends "base.html" %}
{% block title %}Account{% endblock %}
{% block content %}
<div class="container">
    <h1>Account Settings</h1>

    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h2>Profile Information</h2>
                </div>
                <div class="card-body">
                    <p><strong>Username:</strong> {{ session.user_id }}</p>
                    <p><strong>Joined:</strong> {{ user.joined_date }}</p>
                    <p><strong>Status:</strong> 
                        {% if user.payment_status == "Paid" %}
                        <span class="badge bg-success">Paid</span>
                        {% else %}
                        <span class="badge bg-warning">Pending</span>
                        {% endif %}
                    </p>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    <h2>Subscription</h2>
                </div>
                <div class="card-body">
                    <p><strong>Current Plan:</strong> {{ user.plan }}</p>
                    <p><strong>Words Remaining:</strong> {{ words_remaining }}</p>
                    <div class="progress mb-3">
                        <div class="progress-bar" role="progressbar" 
                             style="width: {{ (plan.word_limit - words_remaining) / plan.word_limit * 100 }}%;">
                            {{ ((plan.word_limit - words_remaining) / plan.word_limit * 100) | round }}%
                        </div>
                    </div>

                    <div class="d-grid gap-2">
                        <a href="{{ url_for('pricing') }}" class="btn btn-primary">Manage Plan</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card mb-4">
                <div class="card-header">
                    <h2>Payment History</h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Plan</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th>Reference</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if transactions %}
                                    {% for transaction in transactions %}
                                    <tr>
                                        <td>{{ transaction.timestamp }}</td>
                                        <td>{{ transaction.subscription_type }}</td>
                                        <td>${{ transaction.amount }}</td>
                                        <td>
                                            {% if transaction.status == 'completed' %}
                                            <span class="badge bg-success">Completed</span>
                                            {% elif transaction.status == 'pending' %}
                                            <span class="badge bg-warning">Pending</span>
                                            {% else %}
                                            <span class="badge bg-secondary">{{ transaction.status }}</span>
                                            {% endif %}
                                        </td>
                                        <td>{{ transaction.reference }}</td>
                                    </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5" class="text-center">No payment history available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h2>API Integration</h2>
                </div>
                <div class="card-body">
                    <p>You can integrate with third-party AI detection services by configuring API keys.</p>
                    <div class="d-grid gap-2">
                        <a href="{{ url_for('api_integration') }}" class="btn btn-outline-primary">Configure API Keys</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-4">
        <a href="{{ url_for('dashboard') }}" class="btn btn-secondary">Back to Dashboard</a>
    </div>
</div>
{% endblock %}
"""

if 'base.html' not in html_templates:
    html_templates['base.html'] = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Andikar AI{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Andikar AI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    {% if session.user_id %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('dashboard') }}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('humanize') }}">Humanize</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('detect') }}">Detect AI</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('pricing') }}">Pricing</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('faq') }}">FAQ</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    {% if session.user_id %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown">
                            {{ session.user_id }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{{ url_for('account') }}">Account</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('api_integration') }}">API Integration</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{ url_for('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('register') }}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4 mb-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category if category != 'message' else 'info' }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    {% block content %}{% endblock %}

    <footer class="bg-dark text-white text-center py-4 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>Andikar AI</h5>
                    <p>Making AI text more human.</p>
                </div>
                <div class="col-md-4">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="{{ url_for('index') }}" class="text-white">Home</a></li>
                        <li><a href="{{ url_for('faq') }}" class="text-white">FAQ</a></li>
                        <li><a href="{{ url_for('community') }}" class="text-white">Community</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h5>Contact</h5>
                    <p>support@andikar.ai</p>
                </div>
            </div>
            <div class="mt-3">
                <p>&copy; 2025 Andikar AI. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/script.js"></script>
</body>
</html>
"""

if 'index.html' not in html_templates:
    html_templates['index.html'] = """
{% extends "base.html" %}
{% block title %}Home - Andikar AI{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron text-center my-5 py-5">
        <h1 class="display-4">Welcome to Andikar AI</h1>
        <p class="lead">Humanize your AI-generated text with our advanced processing technology</p>
        <hr class="my-4">
        <p>Transform robotic-sounding AI content into natural, human-like writing with our simple tools.</p>
        <div class="mt-4">
            <a class="btn btn-primary btn-lg" href="{{ url_for('register') }}" role="button">Get Started</a>
            <a class="btn btn-outline-secondary btn-lg ms-2" href="{{ url_for('faq') }}" role="button">Learn More</a>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body text-center">
                    <i class="fas fa-sync fa-4x mb-3 text-primary"></i>
                    <h3 class="card-title">Humanize Text</h3>
                    <p class="card-text">Convert AI-generated text into natural-sounding human writing that passes AI detection tools.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body text-center">
                    <i class="fas fa-search fa-4x mb-3 text-primary"></i>
                    <h3 class="card-title">Detect AI Content</h3>
                    <p class="card-text">Check if text was written by AI or a human with our accurate detection tool.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body text-center">
                    <i class="fas fa-code fa-4x mb-3 text-primary"></i>
                    <h3 class="card-title">API Integration</h3>
                    <p class="card-text">Integrate our tools directly into your workflow with our developer-friendly API.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row my-5">
        <div class="col-md-6">
            <h2>Why Choose Andikar AI?</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><i class="fas fa-check text-success me-2"></i> Natural language processing for human-like text</li>
                <li class="list-group-item"><i class="fas fa-check text-success me-2"></i> Passes AI detection tools</li>
                <li class="list-group-item"><i class="fas fa-check text-success me-2"></i> Simple, easy-to-use interface</li>
                <li class="list-group-item"><i class="fas fa-check text-success me-2"></i> Flexible subscription options</li>
                <li class="list-group-item"><i class="fas fa-check text-success me-2"></i> Developer-friendly API</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h2>Get Started Today</h2>
            <p>Create your account to start humanizing your AI-generated content:</p>
            <ol>
                <li>Register for an account</li>
                <li>Choose your subscription plan</li>
                <li>Start humanizing your content</li>
            </ol>
            <p>Try our Free plan to test the service, then upgrade to unlock more features.</p>
            <a href="{{ url_for('register') }}" class="btn btn-primary">Create an Account</a>
        </div>
    </div>
</div>
{% endblock %}
"""

if 'login.html' not in html_templates:
    html_templates['login.html'] = """
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Login</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ url_for('login') }}">
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                    <div class="mt-3 text-center">
                        <p>Don't have an account? <a href="{{ url_for('register') }}">Register</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
"""

if 'register.html' not in html_templates:
    html_templates['register.html'] = """
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Register</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ url_for('register') }}">
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email Address</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone" class="form-label">Phone Number (Optional)</label>
                            <input type="text" class="form-control" id="phone" name="phone" placeholder="07XXXXXXXX">
                            <div class="form-text">A valid phone number is required for payment processing.</div>
                        </div>
                        
                        <div class="mb-3">
                            <label class="form-label">Select a Plan</label>
                            <div class="row">
                                {% for plan_name, plan in pricing_plans.items() %}
                                <div class="col-md-4 mb-3">
                                    <div class="card h-100">
                                        <div class="card-header {% if plan_name == 'Premium' %}bg-success text-white{% elif plan_name == 'Basic' %}bg-info text-white{% else %}bg-light{% endif %}">
                                            <h5 class="card-title text-center mb-0">{{ plan_name }}</h5>
                                        </div>
                                        <div class="card-body">
                                            <h3 class="text-center mb-3">
                                                {% if plan.price == 0 %}Free{% else %}${{ plan.price }}{% endif %}
                                            </h3>
                                            <ul class="list-unstyled">
                                                <li><i class="fas fa-check text-success me-2"></i> {{ plan.word_limit }} words</li>
                                                <li><i class="fas fa-check text-success me-2"></i> AI detection</li>
                                                <li><i class="fas fa-check text-success me-2"></i> Text humanizing</li>
                                            </ul>
                                        </div>
                                        <div class="card-footer bg-white border-top-0">
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="plan_type" id="plan_{{ plan_name }}" value="{{ plan_name }}" {% if plan_name == 'Free' %}checked{% endif %}>
                                                <label class="form-check-label" for="plan_{{ plan_name }}">
                                                    Select {{ plan_name }} Plan
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                    <div class="mt-3 text-center">
                        <p>Already have an account? <a href="{{ url_for('login') }}">Login</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
"""

# Add other necessary templates like this
# Base templates should be included
# Make sure they are available when referenced in app.py
